---
title: "nuevas clases y red"
author: "María Morales Bravo"
date: "18/8/2021"
output:
  html_document:
    df_print: paged
  word_document: default
---
```{r}
library(dplyr)
library(knitr)
library(ggplot2)
library(ggrepel)
library(magrittr)
library(readxl)
library(writexl)
library(magrittr)
library(ggplot2)

library(readr)
library(kableExtra)
library(flextable)
library(scales)
library(arsenal)
library(tidyr)
library(listdown)
library(plotly)
library(purrr)
library(gridExtra)
library(grid)
#parte7
library(lmtest)
library(tidymodels)
library(vcd)
library(e1071)
library(doParallel)
library(mlbench)
library(parsnip)
library(recipes)
library(tune)
library(pROC)
library(stats)
library(themis)
library(workflows)

#random forest
library(randomForest)


library(caret)
library(rsample)
library(recipes)
#parte 8 
library(FactoMineR)
library(missMDA)
library(factoextra)
library("enrichwith")
library(pls)

#red nueronal 
library(neuralnet) 
library(NeuralNetTools)
load("r_parte1.RData")
load("r_parte2.RData")
load("r_parte3.RData")
load("r_parte4.RData")
load("r_parte5.RData")
load("r_parte6.RData")
load("r_parte7.RData")
load("r_parte8.RData")
load("r_parte9.RData")
```

#CREACION DE NUEVOS GRUPOS


```{r}
colnames(datos_test)[c(18:25)]
colnames(datos_train)[c(18:25)]
nombresmed<-colnames(datos_test)[c(18:25)]

#colnames(datos_test)[c(18:25,55)]
datos_train2<-datos_train#[,-c(18:25,55)]
datos_test2<-datos_test#[,-c(18:25,55)]


datos_train2$eim_muerte<-as.numeric(datos_train2$eim_muerte)
datos_train2$eim_muerte[as.numeric(datos_train2$eim_muerte)==1]=0
datos_train2$eim_muerte[as.numeric(datos_train2$eim_muerte)==2]=1

datos_test2$eim_muerte<-as.numeric(datos_test2$eim_muerte)
datos_test2$eim_muerte[as.numeric(datos_test2$eim_muerte)==1]=0
datos_test2$eim_muerte[as.numeric(datos_test2$eim_muerte)==2]=1

#for(i in 1:dim(datos_train2)[1]){
for(j in nombresmed){
    datos_train2[,j][[1]]<-as.numeric(datos_train2[,j][[1]])
    datos_train2[,j][[1]][as.numeric(datos_train2[,j][[1]])==1]=0
    datos_train2[,j][[1]][as.numeric(datos_train2[,j][[1]])==2]=1
}
#}
table(datos_train2$ant_tpAntiagregantes)

for(j in nombresmed){
    datos_test2[,j][[1]]<-as.numeric(datos_test2[,j][[1]])
    datos_test2[,j][[1]][as.numeric(datos_test2[,j][[1]])==1]=0
    datos_test2[,j][[1]][as.numeric(datos_test2[,j][[1]])==2]=1
}
#}
table(datos_test2$ant_tpAntiagregantes)

#datos_train nuevas categorias
datos_train2$m_antiagregantes=datos_train2$eim_muerte*datos_train2$ant_tpAntiagregantes
datos_train2$m_antiagregantes<-as.factor(datos_train2$m_antiagregantes)
datos_train2$m_anticoagulantes=datos_train2$eim_muerte*datos_train2$ant_tpAnticoagulantes
datos_train2$m_estatinas=datos_train2$eim_muerte*datos_train2$ant_tpEstatinas
datos_train2$m_antihipertensivos=datos_train2$eim_muerte*datos_train2$ant_tpAntihipertensivos
datos_train2$m_antidiabeticos=datos_train2$eim_muerte*datos_train2$ant_tpAntidiabeticos
datos_train2$m_otros=datos_train2$eim_muerte*datos_train2$ant_tpOtrosTratamientos
datos_train2$m_ninguno=datos_train2$eim_muerte*datos_train2$ant_tpNinguno
colnames(datos_train2)[c(18:25,55)]
datos_train2<-datos_train2[,-c(18:25,55)]


#datos_test
datos_test2$m_antiagregantes=datos_test2$eim_muerte*datos_test2$ant_tpAntiagregantes
datos_test2$m_antiagregantes<-as.factor(datos_test2$m_antiagregantes)
datos_test2$m_anticoagulantes=datos_test2$eim_muerte*datos_test2$ant_tpAnticoagulantes
datos_test2$m_estatinas=datos_test2$eim_muerte*datos_test2$ant_tpEstatinas
datos_test2$m_antihipertensivos=datos_test2$eim_muerte*datos_test2$ant_tpAntihipertensivos
datos_test2$m_antidiabeticos=datos_test2$eim_muerte*datos_test2$ant_tpAntidiabeticos
datos_test2$m_otros=datos_test2$eim_muerte*datos_test2$ant_tpOtrosTratamientos
datos_test2$m_ninguno=datos_test2$eim_muerte*datos_test2$ant_tpNinguno
colnames(datos_test2)[c(18:25,55)]
datos_test2<-datos_test2[,-c(18:25,55)]
colnames(datos_test2)[49:55]


#preparar datos 
transformer_ant <- recipe(
                  formula = m_antiagregantes ~ .,
                  data =  datos_train2
               ) %>%
               step_naomit(all_predictors()) %>%
               step_nzv(all_predictors()) %>%
               step_center(all_numeric(), -all_outcomes()) %>%
               step_scale(all_numeric(), -all_outcomes()) %>%
               step_dummy(all_nominal(), -all_outcomes())

transformer_fit_ant <- prep(transformer_ant)

datos_train_prep_ant <- bake(transformer_fit_ant, new_data = datos_train2)
datos_test_prep_ant  <- bake(transformer_fit_ant, new_data = datos_test2)
glimpse(datos_train_prep_ant)


#modelo 
fitted_logistic_model_ant<- logistic_reg() %>%
        # Set the engine
        set_engine("glm") %>%
        # Set the mode
        set_mode("classification") %>%
        # Fit the model
        fit(factor(m_antiagregantes)~., data = datos_train_prep_ant)
tidy(fitted_logistic_model_ant)

#significativos odds
tidy(fitted_logistic_model_ant, exponentiate = TRUE) %>%
  filter(p.value < 0.05)

sig<-tidy(fitted_logistic_model_ant, exponentiate = TRUE) %>%
  filter(p.value < 0.05)
paste(c("Los significativos son:",sig[,1][[1]]))

# Class prediction
pred_class <- predict(fitted_logistic_model_ant,
                      new_data = datos_test_prep_ant,
                      type = "class")
# Prediction Probabilities
pred_proba <- predict(fitted_logistic_model_ant,
                      new_data = datos_test_prep_ant,
                      type = "prob")

pred_proba[1:5,]

#resultados
results <- datos_test_prep_ant %>%
  select(m_antiagregantes) %>%
  bind_cols(pred_class, pred_proba)

results[1:5, ]

#matriz de confusion
conf_mat(results, truth = m_antiagregantes,
         estimate = .pred_class)

#accuracy
accuracy(results, truth = m_antiagregantes,
         estimate = .pred_class)
#sensibilidad
sens(results, truth =  m_antiagregantes,
    estimate = .pred_class)
#especificidad
spec(results, truth =  m_antiagregantes,
    estimate = .pred_class)
#presición
# precision(results, truth =  eim_muerte,
#     estimate = .pred_class)

f_meas(results, truth =  m_antiagregantes,
       estimate = .pred_class)
#kappa
kap(results, truth =  m_antiagregantes,
    estimate = .pred_class)

metricas_ant<-data.frame(rbind(accuracy(results, truth = m_antiagregantes,
         estimate = .pred_class),sens(results, truth =  m_antiagregantes,
    estimate = .pred_class),spec(results, truth =  m_antiagregantes,
    estimate = .pred_class),f_meas(results, truth =  m_antiagregantes,
       estimate = .pred_class),kap(results, truth =  m_antiagregantes,
    estimate = .pred_class)))

metricas<-metricas_ant[,c(1,3)]
colnames(metricas)=c("Medida de bondad de ajuste", "estimación_ant")
metricas

```

# RED NEURONAL 


```{r,echo=F}
# library(neuralnet)
n <- names(datos_train_prep)
length(n)
f <- as.formula(paste("eim_muerte ~",paste(n[!n %in% "eim_muerte"],collapse = " + ")))


nn <- neuralnet(f,data=datos_train_prep, hidden=c(2),linear.output=F, threshold=0.01)
# Respuesta de la Red
pr.nn<-compute(nn,datos_test_prep[,1:99])
pr.nn

plot(nn, rep="best")
# library(gamlss.add)
# library(devtools)



nn2 <- neuralnet(f,data=datos_train_prep, hidden=c(5,3),linear.output=F, threshold=0.01)
# Respuesta de la Red
pr.nn2<-compute(nn2,datos_test_prep[,1:99])
pr.nn2

plot(nn2, rep="best")

nn$act.fct # Activation function
unlist(nn$weights)  # Obtener en formas de vector los weigths=pesos



#red dos capas 
mod3 <- neuralnet(f,data=datos_train_prep, hidden=c(7,3,2),linear.output=F, threshold=0.01)
plot(mod3, rep="best")

#plotnet(nn, circle_cex = 3)
```




```{r,echo=F}
save.image(file = "r_parte10.RData")
```
