---
title: "Combinaciones de medicamentos y regresión con ROSE"
author: "María Morales Bravo"
date: "13/9/2021"
output:
  html_document:
    df_print: paged
  pdf_document: default
---
```{r packages, include = FALSE, echo=F}

library(dplyr)
library(knitr)
library(ggplot2)
library(ggrepel)
library(magrittr)
library(readxl)
library(writexl)
library(magrittr)
library(ggplot2)

library(readr)
library(kableExtra)
library(flextable)
library(scales)
library(arsenal)
library(tidyr)
library(listdown)
library(plotly)
library(purrr)
library(gridExtra)
library(grid)
#parte7
library(lmtest)
library(tidymodels)
library(vcd)
library(e1071)
library(doParallel)
#library(mlbench)
library(parsnip)
library(recipes)
library(tune)
library(pROC)
library(stats)
library(themis)
library(workflows)

#random forest
library(randomForest)


library(caret)
library(rsample)
library(recipes)
#parte 8 
library(FactoMineR)
library(missMDA)
library(factoextra)
library("enrichwith")
library(pls)
library("ROSE")

#red nueronal 
library(neuralnet) 
library(NeuralNetTools)
load("r_parte1.RData")
load("r_parte2.RData")
load("r_parte3.RData")
load("r_parte4.RData")
load("r_parte5.RData")
load("r_parte6.RData")
load("r_parte7.RData")
load("r_parte8.RData")
load("r_parte9.RData")
load("r_parte11a.RData")
```

datos con dos medicamentos 
```{r}
datos_comb2_train<-datos_train_prep[,-c(41:47)]
datos_comb2_test<-datos_test_prep[,-c(41:47)]

med_train<-datos_train_prep[,c(41:47)]
med_test<-datos_test_prep[,c(41:47)]


a<-gtools::combinations(7,2,c(1:7))
anadir_train_com2<-c()
for(n in 1:21){
  i<-a[n,1]
  j<-a[n,2]
  #print(paste("combinación de ",names(med_train)[i],"y",names(med_train)[j]))
  med2<-apply(cbind(med_train[,i],med_train[,j],med_train[,q]),1,sum)
  med2[which(med2==1)]=0
  med2[which(med2==2)]=1
  anadir_train_com2<-cbind(anadir_train_com2,med2)
  #colnames(anadir_train_com2)<-c(colnames(anadir_train_com2)[-c(dim(anadir_train_com2)[2])],paste(names(med_train)[i]," y",names(med_train)[j]))
  colnames(anadir_train_com2)<-gsub( " ", "",c(colnames(anadir_train_com2)[-c(dim(anadir_train_com2)[2])],paste(names(med_train)[i],".",names(med_train)[j])))
  
}

anadir_test_com2<-c()
for(n in 1:21){
  i<-a[n,1]
  j<-a[n,2]
  #print(paste("combinación de ",names(med_test)[i],"y",names(med_test)[j]))
  med2<-apply(cbind(med_test[,i],med_test[,j],med_test[,q]),1,sum)
  med2[which(med2==1)]=0
  med2[which(med2==2)]=1
  anadir_test_com2<-cbind(anadir_test_com2,med2)
  colnames(anadir_test_com2)<-gsub( " ", "",c(colnames(anadir_test_com2)[-c(dim(anadir_test_com2)[2])],paste(names(med_test)[i],".",names(med_test)[j])))
  
}
```


datos con 3 medicamentos a la vez 

```{r}
b<-gtools::combinations(7,3,c(1:7))
anadir_train_com3<-c()
for(n in 1:35){
  i<-b[n,1]
  j<-b[n,2]
  q<-b[n,3]
  #print(paste("combinación de ",names(med_train)[i],",",names(med_train)[j],"y",names(med_train)[q]))
  med3<-apply(cbind(med_train[,i],med_train[,j],med_train[,q]),1,sum)
  med3[which(med3==1)]=0
  med3[which(med3==2)]=0
  med3[which(med3==3)]=1
  anadir_train_com3<-cbind(anadir_train_com3,med3)
  # ejemplo colnames(anadir_test_com2)<-gsub( " ", "",c(colnames(anadir_test_com2)[-c(dim(anadir_test_com2)[2])],paste(names(med_test)[i],".",names(med_test)[j])))
  colnames(anadir_train_com3)<-gsub( " ", "",c(colnames(anadir_train_com3)[-c(dim(anadir_train_com3)[2])],paste(names(med_train)[i],".",names(med_train)[j],".",names(med_train)[q])))
  
}

anadir_test_com3<-c()
for(n in 1:35){
  i<-b[n,1]
  j<-b[n,2]
  q<-b[n,3]
  #print(paste("combinación de ",names(med_test)[i],",",names(med_test)[j],"y",names(med_test)[q]))
  med3<-apply(cbind(med_test[,i],med_test[,j],med_test[,q]),1,sum)
  med3[which(med3==1)]=0
  med3[which(med3==2)]=0
  med3[which(med3==3)]=1
  anadir_test_com3<-cbind(anadir_test_com3,med3)
  colnames(anadir_test_com3)<-gsub( " ", "",c(colnames(anadir_test_com3)[-c(dim(anadir_test_com3)[2])],paste(names(med_test)[i],".",names(med_test)[j],".",names(med_test)[q])))
  
}

```

datos con 4 medicamentos a la vez 

```{r}
c<-gtools::combinations(7,4,c(1:7))
anadir_train_com4<-c()
for(n in 1:35){
  i<-c[n,1]
  j<-c[n,2]
  q<-c[n,3]
  m<-c[n,4]
  #print(paste("combinación de ",names(med_train)[i],",",names(med_train)[j],"y",names(med_train)[q]))
  med4<-apply(cbind(med_train[,i],med_train[,j],med_train[,q],med_train[,m]),1,sum)
  med4[which(med4==1)]=0
  med4[which(med4==2)]=0
  med4[which(med4==3)]=0
  med4[which(med4==4)]=1
  anadir_train_com4<-cbind(anadir_train_com4,med4)
  # ejemplo colnames(anadir_test_com2)<-gsub( " ", "",c(colnames(anadir_test_com2)[-c(dim(anadir_test_com2)[2])],paste(names(med_test)[i],".",names(med_test)[j])))
  colnames(anadir_train_com4)<-gsub( " ", "",c(colnames(anadir_train_com4)[-c(dim(anadir_train_com4)[2])],paste(names(med_train)[i],".",names(med_train)[j],".",names(med_train)[q],".",names(med_train)[m])))
  
}

anadir_test_com4<-c()
for(n in 1:35){
  i<-c[n,1]
  j<-c[n,2]
  q<-c[n,3]
  m<-c[n,4]
  #print(paste("combinación de ",names(med_test)[i],",",names(med_test)[j],"y",names(med_test)[q]))
  med4<-apply(cbind(med_test[,i],med_test[,j],med_test[,q],med_test[,m]),1,sum)
  med4[which(med4==1)]=0
  med4[which(med4==2)]=0
  med4[which(med4==3)]=0
  med4[which(med4==4)]=1
  anadir_test_com4<-cbind(anadir_test_com4,med4)
  colnames(anadir_test_com4)<-gsub( " ", "",c(colnames(anadir_test_com4)[-c(dim(anadir_test_com4)[2])],paste(names(med_test)[i],".",names(med_test)[j],".",names(med_test)[q],".",names(med_test)[m])))
  
}

```



Hacemos el conjunto train y test para varias combinaciones.

```{r}
datos_train_prep_comb2<- cbind(datos_comb2_train,anadir_train_com2)
datos_test_prep_comb2<-cbind(datos_comb2_test,anadir_test_com2)
datos_train_prep_comb3<- cbind(datos_comb2_train,anadir_train_com3)
datos_test_prep_comb3<-cbind(datos_comb2_test,anadir_test_com3)
datos_train_prep_comb4<- cbind(datos_comb2_train,anadir_train_com4)
datos_test_prep_comb4<-cbind(datos_comb2_test,anadir_test_com4)
```

Aplicamos la regresion que mejor hemos visto que se adecua a nuestros datos.


# PRUEBA COMBINACIONES

```{r,echo=F}

rose_train<-ROSE(formula = eim_muerte ~ .,
                  data =  datos_train_prep_comb2,seed=1)$data
# roseboth<-ovun.sample(formula = eim_muerte ~ .,
#                   data =  datos_train,method = "both",p=0.5,seed=1)$data
#
# rose <- ROSE(formula = eim_muerte ~ .,data =  datos_train_prep_comb2, seed=3)$data
# rose

rose_test = ROSE(formula = eim_muerte ~ .,data =  datos_test_prep_comb2)$data
#rose_test_valid=rbind(roseN,rose_test)
#table(rose_test_valid$eim_muerte)

#modelo
fitted_logistic_model<- logistic_reg() %>%
        # Set the engine
        set_engine("glm") %>%
        # Set the mode
        set_mode("classification") %>%
        # Fit the model
        fit(eim_muerte~., data = rose_train)
tidy(fitted_logistic_model)

#significativos odds
tidy(fitted_logistic_model, exponentiate = TRUE) %>%
  filter(p.value < 0.05)

sig<-tidy(fitted_logistic_model, exponentiate = TRUE) %>%
  filter(p.value < 0.05)
paste(c("Los significativos son:",sig[,1][[1]]))
Tablas(sig)

# Class prediction
pred_class <- predict(fitted_logistic_model,
                      new_data = rose_test,
                      type = "class")
# Prediction Probabilities
pred_proba <- predict(fitted_logistic_model,
                      new_data = rose_test,
                      type = "prob")

pred_proba[1:5,]

#resultados
results <- rose_test %>%
  select(eim_muerte) %>%
  bind_cols(pred_class, pred_proba)

results[1:5, ]

results[,1]<-as.factor(results[,1])
#matriz de confusion
conf_mat(results, truth = eim_muerte,
         estimate = .pred_class)

#accuracy
accuracy(results, truth = eim_muerte,
         estimate = .pred_class)
#sensibilidad
sens(results, truth =  eim_muerte,
    estimate = .pred_class)
#especificidad
spec(results, truth =  eim_muerte,
    estimate = .pred_class)
#presición
# precision(results, truth =  eim_muerte,
#     estimate = .pred_class)

f_meas(results, truth =  eim_muerte,
       estimate = .pred_class)
#kappa
kap(results, truth =  eim_muerte,
    estimate = .pred_class)

metricas<-data.frame(rbind(accuracy(results, truth = eim_muerte,
         estimate = .pred_class),sens(results, truth =  eim_muerte,
    estimate = .pred_class),spec(results, truth =  eim_muerte,
    estimate = .pred_class),f_meas(results, truth =  eim_muerte,
       estimate = .pred_class),kap(results, truth =  eim_muerte,
    estimate = .pred_class)))

metricas<-metricas[,c(1,3)]
colnames(metricas)=c("Medida de bondad de ajuste", "estimación")
metricas


#solo significativas
f <- as.formula(paste("eim_muerte ~",paste(sig[,1][[1]][-1] , collapse = " + ")))

#modelo
fitted_logistic_model<- logistic_reg() %>%
        # Set the engine
        set_engine("glm") %>%
        # Set the mode
        set_mode("classification") %>%
        # Fit the model
        fit(f, data = rose_train)
tidy(fitted_logistic_model)

#significativos odds
tidy(fitted_logistic_model, exponentiate = TRUE) %>%
  filter(p.value < 0.05)

sig<-tidy(fitted_logistic_model, exponentiate = TRUE) %>%
  filter(p.value < 0.05)
paste(c("Los significativos son:",sig[,1][[1]]))
Tablas(sig)

# Class prediction
pred_class <- predict(fitted_logistic_model,
                      new_data = rose_test,
                      type = "class")
# Prediction Probabilities
pred_proba <- predict(fitted_logistic_model,
                      new_data = rose_test,
                      type = "prob")

pred_proba[1:5,]

#resultados
results <- rose_test %>%
  select(eim_muerte) %>%
  bind_cols(pred_class, pred_proba)

results[1:5, ]

#matriz de confusion
conf_mat(results, truth = eim_muerte,
         estimate = .pred_class)

results[,1]<-as.factor(results[,1])
#accuracy
accuracy(results, truth = eim_muerte,
         estimate = .pred_class)
#sensibilidad
sens(results, truth =  eim_muerte,
    estimate = .pred_class)
#especificidad
spec(results, truth =  eim_muerte,
    estimate = .pred_class)
#presición
# precision(results, truth =  eim_muerte,
#     estimate = .pred_class)

f_meas(results, truth =  eim_muerte,
       estimate = .pred_class)
#kappa
kap(results, truth =  eim_muerte,
    estimate = .pred_class)

metricas<-data.frame(rbind(accuracy(results, truth = eim_muerte,
         estimate = .pred_class),sens(results, truth =  eim_muerte,
    estimate = .pred_class),spec(results, truth =  eim_muerte,
    estimate = .pred_class),f_meas(results, truth =  eim_muerte,
       estimate = .pred_class),kap(results, truth =  eim_muerte,
    estimate = .pred_class)))

metricas<-metricas[,c(1,3)]
colnames(metricas)=c("Medida de bondad de ajuste", "estimación")
metricas
```

Con cross-validacion 5 10 
```{r,echo=F}
recipe_rose<-recipe(
                  formula = eim_muerte ~ .,
                  data =  rose_train
                ) %>%
               # step_nzv(all_predictors()) %>%
               # step_center(all_numeric(), -all_outcomes()) %>%
               # step_scale(all_numeric(), -all_outcomes()) %>%
               # step_dummy(all_nominal(), -all_outcomes()) %>%
               themis::step_rose(eim_muerte)%>%
                recipes::step_naomit(everything(), skip = TRUE)

fglm_fit <-
  logistic_reg() %>%
  set_engine("glm")


glmbin_rose_wflw <-  workflow() %>%
  add_model(fglm_fit) %>%
  add_recipe(recipe_rose)


cv_folds <- vfold_cv(rose_train, strata = "eim_muerte", repeats = 5)



glmbin_rose_1=glmbin_rose_wflw%>%
  fit_resamples(resamples=cv_folds,
metrics = metric_set(roc_auc,yardstick::accuracy,sens,spec,kap),#,accuracy,sens, spec),
control = control_resamples(save_pred = TRUE))


glmbin_rose<-rbind(collect_metrics(glmbin_rose_1))
glmbin_rose

mat<-conf_mat_resampled(glmbin_rose_1, parameters = NULL, tidy = F)
sensibilidad<-mat[[1]][1,1]/(mat[[1]][2,1]+mat[[1]][1,1])
especificidad <- mat[[1]][2,2]/(mat[[1]][1,2]+mat[[1]][2,2])
accuracy<-(mat[[1]][2,2]+mat[[1]][1,1])/(mat[[1]][2,2]+mat[[1]][1,1]+mat[[1]][1,2]+mat[[1]][2,1])
print(paste("la sensibilidad resulta ", sensibilidad, ", la especificidad ",especificidad, "y accuracy",accuracy))
```

# COMBINACION DE 3

```{r,echo=F}

rose_train<-ROSE(formula = eim_muerte ~ .,
                  data =  datos_train_prep_comb3,seed=1)$data
# roseboth<-ovun.sample(formula = eim_muerte ~ .,
#                   data =  datos_train,method = "both",p=0.5,seed=1)$data
#
# rose <- ROSE(formula = eim_muerte ~ .,data =  datos_train_prep_comb2, seed=3)$data
# rose

rose_test = ROSE(formula = eim_muerte ~ .,data =  datos_test_prep_comb3)$data
#rose_test_valid=rbind(roseN,rose_test)
#table(rose_test_valid$eim_muerte)

#modelo
fitted_logistic_model<- logistic_reg() %>%
        # Set the engine
        set_engine("glm") %>%
        # Set the mode
        set_mode("classification") %>%
        # Fit the model
        fit(eim_muerte~., data = rose_train)
tidy(fitted_logistic_model)

#significativos odds
tidy(fitted_logistic_model, exponentiate = TRUE) %>%
  filter(p.value < 0.05)

sig<-tidy(fitted_logistic_model, exponentiate = TRUE) %>%
  filter(p.value < 0.05)
paste(c("Los significativos son:",sig[,1][[1]]))

# Class prediction
pred_class <- predict(fitted_logistic_model,
                      new_data = rose_test,
                      type = "class")
# Prediction Probabilities
pred_proba <- predict(fitted_logistic_model,
                      new_data = rose_test,
                      type = "prob")

pred_proba[1:5,]

#resultados
results <- rose_test %>%
  select(eim_muerte) %>%
  bind_cols(pred_class, pred_proba)

results[1:5, ]

#matriz de confusion
conf_mat(results, truth = eim_muerte,
         estimate = .pred_class)

results[,1]<-as.factor(results[,1])
#accuracy
accuracy(results, truth = eim_muerte,
         estimate = .pred_class)
#sensibilidad
sens(results, truth =  eim_muerte,
    estimate = .pred_class)
#especificidad
spec(results, truth =  eim_muerte,
    estimate = .pred_class)
#presición
# precision(results, truth =  eim_muerte,
#     estimate = .pred_class)

f_meas(results, truth =  eim_muerte,
       estimate = .pred_class)
#kappa
kap(results, truth =  eim_muerte,
    estimate = .pred_class)

metricas<-data.frame(rbind(accuracy(results, truth = eim_muerte,
         estimate = .pred_class),sens(results, truth =  eim_muerte,
    estimate = .pred_class),spec(results, truth =  eim_muerte,
    estimate = .pred_class),f_meas(results, truth =  eim_muerte,
       estimate = .pred_class),kap(results, truth =  eim_muerte,
    estimate = .pred_class)))

metricas<-metricas[,c(1,3)]
colnames(metricas)=c("Medida de bondad de ajuste", "estimación")
metricas


#solo significativas
f <- as.formula(paste("eim_muerte ~",paste(sig[,1][[1]][-1] , collapse = " + ")))

#modelo
fitted_logistic_model<- logistic_reg() %>%
        # Set the engine
        set_engine("glm") %>%
        # Set the mode
        set_mode("classification") %>%
        # Fit the model
        fit(f, data = rose_train)
tidy(fitted_logistic_model)

#significativos odds
tidy(fitted_logistic_model, exponentiate = TRUE) %>%
  filter(p.value < 0.05)

sig<-tidy(fitted_logistic_model, exponentiate = TRUE) %>%
  filter(p.value < 0.05)
paste(c("Los significativos son:",sig[,1][[1]]))
Tablas(sig)
# Class prediction
pred_class <- predict(fitted_logistic_model,
                      new_data = rose_test,
                      type = "class")
# Prediction Probabilities
pred_proba <- predict(fitted_logistic_model,
                      new_data = rose_test,
                      type = "prob")

pred_proba[1:5,]

#resultados
results <- rose_test %>%
  select(eim_muerte) %>%
  bind_cols(pred_class, pred_proba)

results[1:5, ]

#matriz de confusion
conf_mat(results, truth = eim_muerte,
         estimate = .pred_class)


results[,1]<-as.factor(results[,1])
#accuracy
accuracy(results, truth = eim_muerte,
         estimate = .pred_class)
#sensibilidad
sens(results, truth =  eim_muerte,
    estimate = .pred_class)
#especificidad
spec(results, truth =  eim_muerte,
    estimate = .pred_class)
#presición
# precision(results, truth =  eim_muerte,
#     estimate = .pred_class)

f_meas(results, truth =  eim_muerte,
       estimate = .pred_class)
#kappa
kap(results, truth =  eim_muerte,
    estimate = .pred_class)

metricas<-data.frame(rbind(accuracy(results, truth = eim_muerte,
         estimate = .pred_class),sens(results, truth =  eim_muerte,
    estimate = .pred_class),spec(results, truth =  eim_muerte,
    estimate = .pred_class),f_meas(results, truth =  eim_muerte,
       estimate = .pred_class),kap(results, truth =  eim_muerte,
    estimate = .pred_class)))

metricas<-metricas[,c(1,3)]
colnames(metricas)=c("Medida de bondad de ajuste", "estimación")
metricas
```

# COMBINACION DE 4

```{r,echo=F}

rose_train<-ROSE(formula = eim_muerte ~ .,
                  data =  datos_train_prep_comb4,seed=1)$data
# roseboth<-ovun.sample(formula = eim_muerte ~ .,
#                   data =  datos_train,method = "both",p=0.5,seed=1)$data
#
# rose <- ROSE(formula = eim_muerte ~ .,data =  datos_train_prep_comb2, seed=3)$data
# rose

rose_test = ROSE(formula = eim_muerte ~ .,data =  datos_train_prep_comb4)$data
#rose_test_valid=rbind(roseN,rose_test)
#table(rose_test_valid$eim_muerte)

#modelo
fitted_logistic_model<- logistic_reg() %>%
        # Set the engine
        set_engine("glm") %>%
        # Set the mode
        set_mode("classification") %>%
        # Fit the model
        fit(eim_muerte~., data = rose_train)
tidy(fitted_logistic_model)

#significativos odds
tidy(fitted_logistic_model, exponentiate = TRUE) %>%
  filter(p.value < 0.05)

sig<-tidy(fitted_logistic_model, exponentiate = TRUE) %>%
  filter(p.value < 0.05)
paste(c("Los significativos son:",sig[,1][[1]]))

# Class prediction
pred_class <- predict(fitted_logistic_model,
                      new_data = rose_test,
                      type = "class")
# Prediction Probabilities
pred_proba <- predict(fitted_logistic_model,
                      new_data = rose_test,
                      type = "prob")

pred_proba[1:5,]

#resultados
results <- rose_test %>%
  select(eim_muerte) %>%
  bind_cols(pred_class, pred_proba)

results[1:5, ]

#matriz de confusion
conf_mat(results, truth = eim_muerte,
         estimate = .pred_class)

results[,1]<-as.factor(results[,1])
#accuracy
accuracy(results, truth = eim_muerte,
         estimate = .pred_class)
#sensibilidad
sens(results, truth =  eim_muerte,
    estimate = .pred_class)
#especificidad
spec(results, truth =  eim_muerte,
    estimate = .pred_class)
#presición
# precision(results, truth =  eim_muerte,
#     estimate = .pred_class)

f_meas(results, truth =  eim_muerte,
       estimate = .pred_class)
#kappa
kap(results, truth =  eim_muerte,
    estimate = .pred_class)

metricas<-data.frame(rbind(accuracy(results, truth = eim_muerte,
         estimate = .pred_class),sens(results, truth =  eim_muerte,
    estimate = .pred_class),spec(results, truth =  eim_muerte,
    estimate = .pred_class),f_meas(results, truth =  eim_muerte,
       estimate = .pred_class),kap(results, truth =  eim_muerte,
    estimate = .pred_class)))

metricas<-metricas[,c(1,3)]
colnames(metricas)=c("Medida de bondad de ajuste", "estimación")
metricas


#solo significativas
f <- as.formula(paste("eim_muerte ~",paste(sig[,1][[1]][-1] , collapse = " + ")))

#modelo
fitted_logistic_model<- logistic_reg() %>%
        # Set the engine
        set_engine("glm") %>%
        # Set the mode
        set_mode("classification") %>%
        # Fit the model
        fit(f, data = rose_train)
tidy(fitted_logistic_model)

#significativos odds
tidy(fitted_logistic_model, exponentiate = TRUE) %>%
  filter(p.value < 0.05)

sig<-tidy(fitted_logistic_model, exponentiate = TRUE) %>%
  filter(p.value < 0.05)
paste(c("Los significativos son:",sig[,1][[1]]))
Tablas(sig)
# Class prediction
pred_class <- predict(fitted_logistic_model,
                      new_data = rose_test,
                      type = "class")
# Prediction Probabilities
pred_proba <- predict(fitted_logistic_model,
                      new_data = rose_test,
                      type = "prob")

pred_proba[1:5,]

#resultados
results <- rose_test %>%
  select(eim_muerte) %>%
  bind_cols(pred_class, pred_proba)

results[1:5, ]

#matriz de confusion
conf_mat(results, truth = eim_muerte,
         estimate = .pred_class)


results[,1]<-as.factor(results[,1])
#accuracy
accuracy(results, truth = eim_muerte,
         estimate = .pred_class)
#sensibilidad
sens(results, truth =  eim_muerte,
    estimate = .pred_class)
#especificidad
spec(results, truth =  eim_muerte,
    estimate = .pred_class)
#presición
# precision(results, truth =  eim_muerte,
#     estimate = .pred_class)

f_meas(results, truth =  eim_muerte,
       estimate = .pred_class)
#kappa
kap(results, truth =  eim_muerte,
    estimate = .pred_class)

metricas<-data.frame(rbind(accuracy(results, truth = eim_muerte,
         estimate = .pred_class),sens(results, truth =  eim_muerte,
    estimate = .pred_class),spec(results, truth =  eim_muerte,
    estimate = .pred_class),f_meas(results, truth =  eim_muerte,
       estimate = .pred_class),kap(results, truth =  eim_muerte,
    estimate = .pred_class)))

metricas<-metricas[,c(1,3)]
colnames(metricas)=c("Medida de bondad de ajuste", "estimación")
metricas
```
Con cross-validacion 5 10 
```{r,echo=F}
recipe_rose<-recipe(
                  formula = eim_muerte ~ .,
                  data =  rose_train
                ) %>%
               # step_nzv(all_predictors()) %>%
               # step_center(all_numeric(), -all_outcomes()) %>%
               # step_scale(all_numeric(), -all_outcomes()) %>%
               # step_dummy(all_nominal(), -all_outcomes()) %>%
               themis::step_rose(eim_muerte)%>%
                recipes::step_naomit(everything(), skip = TRUE)

fglm_fit <-
  logistic_reg() %>%
  set_engine("glm")


glmbin_rose_wflw <-  workflow() %>%
  add_model(fglm_fit) %>%
  add_recipe(recipe_rose)


cv_folds <- vfold_cv(rose_train, strata = "eim_muerte", repeats = 5)



glmbin_rose_1=glmbin_rose_wflw%>%
  fit_resamples(resamples=cv_folds,
metrics = metric_set(roc_auc,yardstick::accuracy,sens,spec,kap),#,accuracy,sens, spec),
control = control_resamples(save_pred = TRUE))


glmbin_rose<-rbind(collect_metrics(glmbin_rose_1))
glmbin_rose

mat<-conf_mat_resampled(glmbin_rose_1, parameters = NULL, tidy = F)
sensibilidad<-mat[[1]][1,1]/(mat[[1]][2,1]+mat[[1]][1,1])
especificidad <- mat[[1]][2,2]/(mat[[1]][1,2]+mat[[1]][2,2])
accuracy<-(mat[[1]][2,2]+mat[[1]][1,1])/(mat[[1]][2,2]+mat[[1]][1,1]+mat[[1]][1,2]+mat[[1]][2,1])
print(paste("la sensibilidad resulta ", sensibilidad, ", la especificidad ",especificidad, "y accuracy",accuracy))
```

```{r,echo=F}
save.image(file = "r_parte12.RData")
```
